Data file location of 2019 Survey StackOverflow:

C:\\Users\\admin\\Desktop\\Data Science\\Data for ananlysis\\2019 developer survey Stackoverflow\\

In [1]:
import pandas as pd

In [2]:
df_public=pd.read_csv('C:\\Users\\admin\\Desktop\\Data_Science\\Data_for_ananlysis\\2019 developer survey Stackoverflow\\survey_results_public.csv'\
                     ,index_col='Respondent')
type(df_public)

pandas.core.frame.DataFrame

In [3]:
df_public
#By default jupyter shows 25 columns only

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [4]:
#to view all columns
pd.set_option('display.max_columns',85)
df_public.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [5]:
df_public.shape

(88883, 84)

In [6]:
"""Print a concise summary of a DataFrame.

This method prints information about a DataFrame including
the index dtype and columns, non-null values and memory usage.

"""
df_public.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 88883 entries, 1 to 88863
Data columns (total 84 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   MainBranch              88331 non-null  object
 1   Hobbyist                88883 non-null  object
 2   OpenSourcer             88883 non-null  object
 3   OpenSource              86842 non-null  object
 4   Employment              87181 non-null  object
 5   Country                 88751 non-null  object
 6   Student                 87014 non-null  object
 7   EdLevel                 86390 non-null  object
 8   UndergradMajor          75614 non-null  object
 9   EduOther                84260 non-null  object
 10  OrgSize                 71791 non-null  object
 11  DevType                 81335 non-null  object
 12  YearsCode               87938 non-null  object
 13  Age1stCode              87634 non-null  object
 14  YearsCodePro            74331 non-null  object
 15  CareerSat               72847 non-null  object
 16  JobSat                  70988 non-null  object
 17  MgrIdiot                61159 non-null  object
 18  MgrMoney                61157 non-null  object
 19  MgrWant                 61232 non-null  object
 20  JobSeek                 80555 non-null  object
 21  LastHireDate            79854 non-null  object
 22  LastInt                 67155 non-null  object
 23  FizzBuzz                71344 non-null  object
 24  JobFactors              79371 non-null  object
 25  ResumeUpdate            77877 non-null  object
 26  CurrencySymbol          71392 non-null  object
 27  CurrencyDesc            71392 non-null  object
 28  CompTotal               55945 non-null  float64
 29  CompFreq                63268 non-null  object
 30  ConvertedComp           55823 non-null  float64
 31  WorkWeekHrs             64503 non-null  float64
 32  WorkPlan                68914 non-null  object
 33  WorkChallenge           68141 non-null  object
 34  WorkRemote              70284 non-null  object
 35  WorkLoc                 70055 non-null  object
 36  ImpSyn                  71779 non-null  object
 37  CodeRev                 70390 non-null  object
 38  CodeRevHrs              49790 non-null  float64
 39  UnitTests               62668 non-null  object
 40  PurchaseHow             61108 non-null  object
 41  PurchaseWhat            62029 non-null  object
 42  LanguageWorkedWith      87569 non-null  object
 43  LanguageDesireNextYear  84088 non-null  object
 44  DatabaseWorkedWith      76026 non-null  object
 45  DatabaseDesireNextYear  69147 non-null  object
 46  PlatformWorkedWith      80714 non-null  object
 47  PlatformDesireNextYear  77443 non-null  object
 48  WebFrameWorkedWith      65022 non-null  object
 49  WebFrameDesireNextYear  62944 non-null  object
 50  MiscTechWorkedWith      59586 non-null  object
 51  MiscTechDesireNextYear  64511 non-null  object
 52  DevEnviron              87317 non-null  object
 53  OpSys                   87851 non-null  object
 54  Containers              85366 non-null  object
 55  BlockchainOrg           48175 non-null  object
 56  BlockchainIs            60165 non-null  object
 57  BetterLife              86269 non-null  object
 58  ITperson                87141 non-null  object
 59  OffOn                   86663 non-null  object
 60  SocialMedia             84437 non-null  object
 61  Extraversion            87305 non-null  object
 62  ScreenName              80486 non-null  object
 63  SOVisit1st              83877 non-null  object
 64  SOVisitFreq             88263 non-null  object
 65  SOVisitTo               88086 non-null  object
 66  SOFindAnswer            87816 non-null  object
 67  SOTimeSaved             86344 non-null  object
 68  SOHowMuchTime           68378 non-null  object
 69  SOAccount               87828 non-null  object
 70  SOPartFreq              74692 non-null  object
 71  SOJobs                  88066 non-null  object
 72  EntTeams                87841 non-null  object
 73  SOComm                  88131 non-null  object
 74  WelcomeChange           85855 non-null  object
 75  SONewContent            69560 non-null  object
 76  Age                     79210 non-null  float64
 77  Gender                  85406 non-null  object
 78  Trans                   83607 non-null  object
 79  Sexuality               76147 non-null  object
 80  Ethnicity               76668 non-null  object
 81  Dependents              83059 non-null  object
 82  SurveyLength            86984 non-null  object
 83  SurveyEase              87081 non-null  object
dtypes: float64(5), object(79)
memory usage: 57.6+ MB

In [7]:
df_schema=pd.read_csv('C:\\Users\\admin\\Desktop\\Data_Science\\Data_for_ananlysis\\2019 developer survey Stackoverflow\\survey_results_schema.csv'\
                     ,index_col='Column')
df_schema

                                                   QuestionText
Column
Respondent    Randomized respondent ID number (not in order ...
MainBranch    Which of the following options best describes ...
Hobbyist                                Do you code as a hobby?
OpenSourcer         How often do you contribute to open source?
OpenSource    How do you feel about the quality of open sour...
...                                                         ...
Sexuality     Which of the following do you currently identi...
Ethnicity     Which of the following do you identify as? Ple...
Dependents    Do you have any dependents (e.g., children, el...
SurveyLength  How do you feel about the length of the survey...
SurveyEase    How easy or difficult was this survey to compl...

[85 rows x 1 columns]

In [8]:
#To view all rows
pd.set_option('display.max_rows',85)
df_schema

                                                             QuestionText
Column
Respondent              Randomized respondent ID number (not in order ...
MainBranch              Which of the following options best describes ...
Hobbyist                                          Do you code as a hobby?
OpenSourcer                   How often do you contribute to open source?
OpenSource              How do you feel about the quality of open sour...
Employment              Which of the following best describes your cur...
Country                         In which country do you currently reside?
Student                 Are you currently enrolled in a formal, degree...
EdLevel                 Which of the following best describes the high...
UndergradMajor          What was your main or most important field of ...
EduOther                Which of the following types of non-degree edu...
OrgSize                 Approximately how many people are employed by ...
DevType                 Which of the following describe you? Please se...
YearsCode               Including any education, how many years have y...
Age1stCode              At what age did you write your first line of c...
YearsCodePro            How many years have you coded professionally (...
CareerSat               Overall, how satisfied are you with your caree...
JobSat                  How satisfied are you with your current job? (...
MgrIdiot                How confident are you that your manager knows ...
MgrMoney                Do you believe that you need to be a manager t...
MgrWant                 Do you want to become a manager yourself in th...
JobSeek                 Which of the following best describes your cur...
LastHireDate            When was the last time that you took a job wit...
LastInt                 In your most recent successful job interview (...
FizzBuzz                Have you ever been asked to solve FizzBuzz in ...
JobFactors              Imagine that you are deciding between two job ...
ResumeUpdate            Think back to the last time you updated your r...
CurrencySymbol          Which currency do you use day-to-day? If your ...
CurrencyDesc            Which currency do you use day-to-day? If your ...
CompTotal               What is your current total compensation (salar...
CompFreq                 Is that compensation weekly, monthly, or yearly?
ConvertedComp           Salary converted to annual USD salaries using ...
WorkWeekHrs              On average, how many hours per week do you work?
WorkPlan                          How structured or planned is your work?
WorkChallenge           Of these options, what are your greatest chall...
WorkRemote                                How often do you work remotely?
WorkLoc                                   Where would you prefer to work?
ImpSyn                  For the specific work you do, and the years of...
CodeRev                          Do you review code as part of your work?
CodeRevHrs              On average, how many hours per week do you spe...
UnitTests               Does your company regularly employ unit tests ...
PurchaseHow             How does your company make decisions about pur...
PurchaseWhat            What level of influence do you, personally, ha...
LanguageWorkedWith      Which of the following programming, scripting,...
LanguageDesireNextYear  Which of the following programming, scripting,...
DatabaseWorkedWith      Which of the following database environments h...
DatabaseDesireNextYear  Which of the following database environments h...
PlatformWorkedWith      Which of the following platforms have you done...
PlatformDesireNextYear  Which of the following platforms have you done...
WebFrameWorkedWith      Which of the following web frameworks have you...
WebFrameDesireNextYear  Which of the following web frameworks have you...
MiscTechWorkedWith      Which of the following other frameworks, libra...
MiscTechDesireNextYear  Which of the following other frameworks, libra...
DevEnviron              Which development environment(s) do you use re...
OpSys                   What is the primary operating system in which ...
Containers              How do you use containers (Docker, Open Contai...
BlockchainOrg           How is your organization thinking about or imp...
BlockchainIs            Blockchain / cryptocurrency technology is prim...
BetterLife              Do you think people born today will have a bet...
ITperson                 Are you the "IT support person" for your family?
OffOn                         Have you tried turning it off and on again?
SocialMedia                   What social media site do you use the most?
Extraversion              Do you prefer online chat or IRL conversations?
ScreenName                                           What do you call it?
SOVisit1st              To the best of your memory, when did you first...
SOVisitFreq             How frequently would you say you visit Stack O...
SOVisitTo               I visit Stack Overflow to... (check all that a...
SOFindAnswer            On average, how many times a week do you find ...
SOTimeSaved             Think back to the last time you solved a codin...
SOHowMuchTime           About how much time did you save? If you're no...
SOAccount                           Do you have a Stack Overflow account?
SOPartFreq              How frequently would you say you participate i...
SOJobs                  Have you ever used or visited Stack Overflow J...
EntTeams                Have you ever used Stack Overflow for Enterpri...
SOComm                  Do you consider yourself a member of the Stack...
WelcomeChange           Compared to last year, how welcome do you feel...
SONewContent            Would you like to see any of the following on ...
Age                     What is your age (in years)? If you prefer not...
Gender                  Which of the following do you currently identi...
Trans                                     Do you identify as transgender?
Sexuality               Which of the following do you currently identi...
Ethnicity               Which of the following do you identify as? Ple...
Dependents              Do you have any dependents (e.g., children, el...
SurveyLength            How do you feel about the length of the survey...
SurveyEase              How easy or difficult was this survey to compl...

# SELECTING ROWS AND COLUMNS

In [9]:
people={
    "first":["Corey","Jane","John"],
    "last":["Schafer","Doe","Doe"],
    "email":["sflajf@gmail","adjhdj@yahoo","adsfasfd@facebook"]
}

In [10]:
df_p=pd.DataFrame(people)
df_p

   first     last              email
0  Corey  Schafer       sflajf@gmail
1   Jane      Doe       adjhdj@yahoo
2   John      Doe  adsfasfd@facebook

In [11]:
df_p["email"]

0         sflajf@gmail
1         adjhdj@yahoo
2    adsfasfd@facebook
Name: email, dtype: object

In [12]:
type(df_p["email"])

pandas.core.series.Series

In [13]:
#OTher way of accessing columns
df_p.email
#however this may give error if df attribute and column name appears to be same

0         sflajf@gmail
1         adjhdj@yahoo
2    adsfasfd@facebook
Name: email, dtype: object

In [14]:
df_p[["last","first"]]
#Passing list to access multiple columns

      last  first
0  Schafer  Corey
1      Doe   Jane
2      Doe   John

In [15]:
type(df_p[["last","first"]])

pandas.core.frame.DataFrame

In [16]:
df_p.columns
#to view all columns

Index(['first', 'last', 'email'], dtype='object')

In [17]:
#To acees rows: loc & iloc

df_p.iloc[0]

first           Corey
last          Schafer
email    sflajf@gmail
Name: 0, dtype: object

In [18]:
df_p.iloc[[0,1]]

   first     last         email
0  Corey  Schafer  sflajf@gmail
1   Jane      Doe  adjhdj@yahoo

In [19]:
df_p.iloc[[0,1], 2]

0    sflajf@gmail
1    adjhdj@yahoo
Name: email, dtype: object

df.iloc[]:-
Purely integer-location based indexing for selection by position.

``.iloc[]`` is primarily integer position based (from ``0`` to
``length-1`` of the axis), but may also be used with a boolean
array.

In [20]:
df_p.loc[0]

first           Corey
last          Schafer
email    sflajf@gmail
Name: 0, dtype: object

In [21]:
df_p.loc[[0,1]]

   first     last         email
0  Corey  Schafer  sflajf@gmail
1   Jane      Doe  adjhdj@yahoo

In [22]:
df_p.loc[[0,1],'email']

0    sflajf@gmail
1    adjhdj@yahoo
Name: email, dtype: object

In [23]:
df_p.loc[[0,1],['email',"last"]]

          email     last
0  sflajf@gmail  Schafer
1  adjhdj@yahoo      Doe

df.loc[]:-
Access a group of rows and columns by label(s) or a boolean array.

``.loc[]`` is primarily label based, but may also be used with a oolean array.

Difference between loc[] and iloc[]:-

In [24]:
df_public.head(2)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [25]:
df_schema.head(2)

                                                 QuestionText
Column
Respondent  Randomized respondent ID number (not in order ...
MainBranch  Which of the following options best describes ...

In [26]:
df_public.shape

(88883, 84)

In [27]:
df_public["Hobbyist"]

Respondent
1        Yes
2         No
3        Yes
4         No
5        Yes
        ...
88377    Yes
88601     No
88802     No
88816     No
88863    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [28]:
df_public["Hobbyist"].value_counts()

Yes    71257
No     17626
Name: Hobbyist, dtype: int64

In [29]:
df_public.loc[1]

MainBranch                           I am a student who is learning to code
Hobbyist                                                                Yes
OpenSourcer                                                           Never
OpenSource                The quality of OSS and closed source software ...
Employment                           Not employed, and not looking for work
Country                                                      United Kingdom
Student                                                                  No
EdLevel                                           Primary/elementary school
UndergradMajor                                                          NaN
EduOther                  Taught yourself a new language, framework, or ...
OrgSize                                                                 NaN
DevType                                                                 NaN
YearsCode                                                                 4
Age1stCode                                                               10
YearsCodePro                                                            NaN
CareerSat                                                               NaN
JobSat                                                                  NaN
MgrIdiot                                                                NaN
MgrMoney                                                                NaN
MgrWant                                                                 NaN
JobSeek                                                                 NaN
LastHireDate                                                            NaN
LastInt                                                                 NaN
FizzBuzz                                                                NaN
JobFactors                                                              NaN
ResumeUpdate                                                            NaN
CurrencySymbol                                                          NaN
CurrencyDesc                                                            NaN
CompTotal                                                               NaN
CompFreq                                                                NaN
ConvertedComp                                                           NaN
WorkWeekHrs                                                             NaN
WorkPlan                                                                NaN
WorkChallenge                                                           NaN
WorkRemote                                                              NaN
WorkLoc                                                                 NaN
ImpSyn                                                                  NaN
CodeRev                                                                 NaN
CodeRevHrs                                                              NaN
UnitTests                                                               NaN
PurchaseHow                                                             NaN
PurchaseWhat                                                            NaN
LanguageWorkedWith                          HTML/CSS;Java;JavaScript;Python
LanguageDesireNextYear      C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL
DatabaseWorkedWith                                                   SQLite
DatabaseDesireNextYear                                                MySQL
PlatformWorkedWith                                            MacOS;Windows
PlatformDesireNextYear                              Android;Arduino;Windows
WebFrameWorkedWith                                             Django;Flask
WebFrameDesireNextYear                                         Flask;jQuery
MiscTechWorkedWith                                                  Node.js
MiscTechDesireNextYear                                              Node.js
DevEnviron                                       IntelliJ;Notepad++;PyCharm
OpSys                                                               Windows
Containers                                          I do not use containers
BlockchainOrg                                                           NaN
BlockchainIs                                                            NaN
BetterLife                                                              Yes
ITperson                           Fortunately, someone else has that title
OffOn                                                                   Yes
SocialMedia                                                         Twitter
Extraversion                                                         Online
ScreenName                                                         Username
SOVisit1st                                                             2017
SOVisitFreq                                 A few times per month or weekly
SOVisitTo                 Find answers to specific questions;Learn how t...
SOFindAnswer                                             3-5 times per week
SOTimeSaved                                  Stack Overflow was much faster
SOHowMuchTime                                                 31-60 minutes
SOAccount                                                                No
SOPartFreq                                                              NaN
SOJobs                    No, I didn't know that Stack Overflow had a jo...
EntTeams                                No, and I don't know what those are
SOComm                                                              Neutral
WelcomeChange                       Just as welcome now as I felt last year
SONewContent              Tech articles written by other developers;Indu...
Age                                                                    14.0
Gender                                                                  Man
Trans                                                                    No
Sexuality                                           Straight / Heterosexual
Ethnicity                                                               NaN
Dependents                                                               No
SurveyLength                                          Appropriate in length
SurveyEase                                       Neither easy nor difficult
Name: 1, dtype: object

In [30]:
df_public.loc[[1,2,3],'Hobbyist']

Respondent
1    Yes
2     No
3    Yes
Name: Hobbyist, dtype: object

In [31]:
df_public.loc[1:3,'Hobbyist']

Respondent
1    Yes
2     No
3    Yes
Name: Hobbyist, dtype: object

In [32]:
df_public.loc[1:3,['Hobbyist','Country','OffOn']]

           Hobbyist                 Country OffOn
Respondent
1               Yes          United Kingdom   Yes
2                No  Bosnia and Herzegovina   Yes
3               Yes                Thailand   Yes

In [33]:
df_public.loc[1:3,'Hobbyist':'Country']

,Hobbyist,OpenSourcer,OpenSource,Employment,Country
Respondent,,,,,
1,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom
2,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina
3,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand

# INDEXES

In [34]:
df_p

   first     last              email
0  Corey  Schafer       sflajf@gmail
1   Jane      Doe       adjhdj@yahoo
2   John      Doe  adsfasfd@facebook

In [35]:
df_p.set_index("email")
#but this does not modify original dataframe

                   first     last
email
sflajf@gmail       Corey  Schafer
adjhdj@yahoo        Jane      Doe
adsfasfd@facebook   John      Doe

In [36]:
df_p.index

RangeIndex(start=0, stop=3, step=1)

In [37]:
#df_p.set_index("email",inplace=True)
#This will modify the orginal dataframe
df_p

   first     last              email
0  Corey  Schafer       sflajf@gmail
1   Jane      Doe       adjhdj@yahoo
2   John      Doe  adsfasfd@facebook

In [38]:
#Now .loc[] can be given label instead of integer
#df_p.loc['sflajf@gmail']

In [39]:
#df_p.loc['sflajf@gmail','last']

In [38]:
#df_p.loc[0] now this will give error
df_p.iloc[1]
#But iloc[] can be used with integer

first            Jane
last              Doe
email    adjhdj@yahoo
Name: 1, dtype: object

In [39]:
df_p.reset_index(inplace=True)
df_p

   index  first     last              email
0      0  Corey  Schafer       sflajf@gmail
1      1   Jane      Doe       adjhdj@yahoo
2      2   John      Doe  adsfasfd@facebook

In [40]:
df_public.head(1)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [41]:
df_schema.head(2)

                                                 QuestionText
Column
Respondent  Randomized respondent ID number (not in order ...
MainBranch  Which of the following options best describes ...

In [44]:
#df_schema.loc['MainBranch']

In [42]:
df_schema.sort_index(ascending=False, inplace=True)
df_schema.head(5)

                                                   QuestionText
Column
YearsCodePro  How many years have you coded professionally (...
YearsCode     Including any education, how many years have y...
WorkWeekHrs    On average, how many hours per week do you work?
WorkRemote                      How often do you work remotely?
WorkPlan                How structured or planned is your work?

# FILTERING

In [43]:
people={
    "first":["Corey","Jane","John"],
    "last":["Schafer","Doe","Doe"],
    "email":["CS@gmail","JaD@gmail","JoD@gmail"]
}
df_people=pd.DataFrame(people)
df_people

   first     last      email
0  Corey  Schafer   CS@gmail
1   Jane      Doe  JaD@gmail
2   John      Doe  JoD@gmail

In [44]:
df_people["last"]=='Doe'

0    False
1     True
2     True
Name: last, dtype: bool

In [45]:
df_people[df_people["last"]=='Doe']

  first last      email
1  Jane  Doe  JaD@gmail
2  John  Doe  JoD@gmail

In [46]:
filt = (df_people["last"]=='Doe')
print(filt)

0    False
1     True
2     True
Name: last, dtype: bool

In [47]:
df_people[filt]

  first last      email
1  Jane  Doe  JaD@gmail
2  John  Doe  JoD@gmail

In [48]:
df_people.loc[filt]
#loc can accept boolean series

  first last      email
1  Jane  Doe  JaD@gmail
2  John  Doe  JoD@gmail

In [50]:
df_people[filt]['email']

1    JaD@gmail
2    JoD@gmail
Name: email, dtype: object

In [49]:
df_people.loc[filt,'email']

1    JaD@gmail
2    JoD@gmail
Name: email, dtype: object

In [53]:
# & : and
# | : or

In [51]:
filt=(df_people["last"]=="Doe") & (df_people["first"]=="John")
df_people.loc[filt]

  first last      email
2  John  Doe  JoD@gmail

In [52]:
filt=(df_people["last"]=="Schafer") | (df_people["first"]=="John")
df_people.loc[filt]

   first     last      email
0  Corey  Schafer   CS@gmail
2   John      Doe  JoD@gmail

In [53]:
#TO get opposite of filter
filt=(df_people["last"]=="Schafer") | (df_people["first"]=="John")
df_people.loc[-filt]

  first last      email
1  Jane  Doe  JaD@gmail

In [54]:
import pandas as pd
df_public=pd.read_csv('C:\\Users\\admin\\Desktop\\Data_Science\\Data_for_ananlysis\\2019 developer survey Stackoverflow\\survey_results_public.csv'\
                     ,index_col='Respondent')

df_schema=pd.read_csv('C:\\Users\\admin\\Desktop\\Data_Science\\Data_for_ananlysis\\2019 developer survey Stackoverflow\\survey_results_schema.csv'\
                     ,index_col='Column')

In [55]:
df_public.head(1)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [56]:
df_schema.head(2)

                                                 QuestionText
Column
Respondent  Randomized respondent ID number (not in order ...
MainBranch  Which of the following options best describes ...

In [58]:
high_salary_filt=(df_public['ConvertedComp']>70000)
df_public.loc[high_salary_filt,["Country","LanguageWorkedWith","ConvertedComp"]]

,Country,LanguageWorkedWith,ConvertedComp
Respondent,,,
6,Canada,Java;R;SQL,366420.0
9,New Zealand,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,95179.0
13,United States,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,90000.0
16,United Kingdom,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...,455352.0
22,United States,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,103000.0
...,...,...,...
88876,United States,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...,180000.0
88877,United States,Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...,2000000.0
88878,United States,HTML/CSS;JavaScript;Scala;TypeScript,130000.0
88879,Finland,Bash/Shell/PowerShell;C++;Python,82488.0
88882,Netherlands,C#;HTML/CSS;Java;JavaScript;PHP;Python,588012.0

In [59]:
countries=["United States","India",'United Kingdom',"Germany","Canada"]
filt=df_public['Country'].isin(countries)
df_public.loc[filt, 'Country']

Respondent
1        United Kingdom
4         United States
6                Canada
8                 India
10                India
              ...
85642     United States
85961    United Kingdom
86012             India
88282     United States
88377            Canada
Name: Country, Length: 45008, dtype: object

In [60]:
df_public["LanguageWorkedWith"]

Respondent
1                          HTML/CSS;Java;JavaScript;Python
2                                      C++;HTML/CSS;Python
3                                                 HTML/CSS
4                                      C;C++;C#;Python;SQL
5              C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
                               ...
88377                        HTML/CSS;JavaScript;Other(s):
88601                                                  NaN
88802                                                  NaN
88816                                                  NaN
88863    Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...
Name: LanguageWorkedWith, Length: 88883, dtype: object

In [61]:
filt=df_public["LanguageWorkedWith"].str.contains("Python", na=False)
df_public.loc[filt, "LanguageWorkedWith"]

Respondent
1                          HTML/CSS;Java;JavaScript;Python
2                                      C++;HTML/CSS;Python
4                                      C;C++;C#;Python;SQL
5              C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
8        Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
                               ...
84539    Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
85738      Bash/Shell/PowerShell;C++;Python;Ruby;Other(s):
86566      Bash/Shell/PowerShell;HTML/CSS;Python;Other(s):
87739             C;C++;HTML/CSS;JavaScript;PHP;Python;SQL
88212                           HTML/CSS;JavaScript;Python
Name: LanguageWorkedWith, Length: 36443, dtype: object

# MODYFYING DATA WITHIN DATAFRAME

In [62]:
people={
    "first":["Corey","Jane","John"],
    "last":["Schafer","Doe","Doe"],
    "email":["CS@gmail","JaD@gmail","JoD@gmail"]
}
df_people=pd.DataFrame(people)
df_people

   first     last      email
0  Corey  Schafer   CS@gmail
1   Jane      Doe  JaD@gmail
2   John      Doe  JoD@gmail

In [63]:
df_people.columns

Index(['first', 'last', 'email'], dtype='object')

In [64]:
df_people.columns = ["First_name","Last_name","EMails"]
df_people

  First_name Last_name     EMails
0      Corey   Schafer   CS@gmail
1       Jane       Doe  JaD@gmail
2       John       Doe  JoD@gmail

In [65]:
df_people.columns=[x.upper() for x in df_people.columns]
df_people

  FIRST_NAME LAST_NAME     EMAILS
0      Corey   Schafer   CS@gmail
1       Jane       Doe  JaD@gmail
2       John       Doe  JoD@gmail

In [67]:
df_people.columns=df_people.columns.str.replace(" ","_")
df_people

  FIRST_NAME LAST_NAME     EMAILS
0      Corey   Schafer   CS@gmail
1       Jane       Doe  JaD@gmail
2       John       Doe  JoD@gmail

In [68]:
df_people.columns=[x.lower() for x in df_people.columns]
df_people

  first_name last_name     emails
0      Corey   Schafer   CS@gmail
1       Jane       Doe  JaD@gmail
2       John       Doe  JoD@gmail

In [70]:
df_people.rename(columns={'first_name':'first','last_name':'last'})
#This doesnt change original df

   first     last     emails
0  Corey  Schafer   CS@gmail
1   Jane      Doe  JaD@gmail
2   John      Doe  JoD@gmail

In [71]:
df_people

  first_name last_name     emails
0      Corey   Schafer   CS@gmail
1       Jane       Doe  JaD@gmail
2       John       Doe  JoD@gmail

In [72]:
df_people.loc[2]=["John","Smith","JS@gmail"]
df_people

  first_name last_name     emails
0      Corey   Schafer   CS@gmail
1       Jane       Doe  JaD@gmail
2       John     Smith   JS@gmail

In [73]:
df_people.loc[2,["last_name",'emails']]=["Doe","JoD@gmail"]
df_people

  first_name last_name     emails
0      Corey   Schafer   CS@gmail
1       Jane       Doe  JaD@gmail
2       John       Doe  JoD@gmail

In [74]:
filt=(df_people["emails"]=="JoD@gmail")
df_people[filt]["last_name"]='Smith'

#THis gives error

<ipython-input-74-355e07476d0e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_people[filt]["last_name"]='Smith'

In [74]:
filt=(df_people["emails"]=="JoD@gmail")
df_people.loc[filt,"last_name"]='Smith'
df_people

  first_name last_name     emails
0      Corey   Schafer   CS@gmail
1       Jane       Doe  JaD@gmail
2       John     Smith  JoD@gmail

In [75]:
df_people["emails"]=df_people["emails"].str.lower()
df_people

  first_name last_name     emails
0      Corey   Schafer   cs@gmail
1       Jane       Doe  jad@gmail
2       John     Smith  jod@gmail

## apply, map, applymap, replace

In [80]:
df_people["emails"].apply(len)
#apply() -Apply a function along an axis of the DataFrame.

0    8
1    9
2    9
Name: emails, dtype: int64

In [81]:
def update_emails(emails):
    return emails.upper()

In [82]:
df_people['emails']=df_people['emails'].apply(update_emails)
df_people

  first_name last_name     emails
0      Corey   Schafer   CS@GMAIL
1       Jane       Doe  JAD@GMAIL
2       John     Smith  JOD@GMAIL

In [83]:
df_people['emails']=df_people['emails'].apply(lambda x: x.lower())
df_people

  first_name last_name     emails
0      Corey   Schafer   cs@gmail
1       Jane       Doe  jad@gmail
2       John     Smith  jod@gmail

In [81]:
df_people['emails'].apply(len)

0    8
1    9
2    9
Name: emails, dtype: int64

In [84]:
df_people.apply(len)

first_name    3
last_name     3
emails        3
dtype: int64

In [85]:
df_people.apply(len, axis='columns')

0    3
1    3
2    3
dtype: int64

In [85]:
df_people.apply(pd.Series.min)

first_name       Corey
last_name          Doe
emails        cs@gmail
dtype: object

In [86]:
df_people.apply(lambda x: x.min())

first_name       Corey
last_name          Doe
emails        cs@gmail
dtype: object

In [87]:
#applymap works only with df and not series
df_people.applymap(len)
#Apply a function to a Dataframe elementwise.

   first_name  last_name  emails
0           5          7       8
1           4          3       9
2           4          5       9

In [88]:
df_people.applymap(str.lower)

  first_name last_name     emails
0      corey   schafer   cs@gmail
1       jane       doe  jad@gmail
2       john     smith  jod@gmail

In [91]:
df_people

  first_name last_name     emails
0      Corey   Schafer   cs@gmail
1       Jane       Doe  jad@gmail
2       John     Smith  jod@gmail

In [92]:
#map works only with series
df_people['first_name'].map({'Corey':'Chris','Jane':'Mary'})

0    Chris
1     Mary
2      NaN
Name: first_name, dtype: object

In [94]:
#Replace
df_people['first_name'].replace({'Corey':'Chris','Jane':'Mary'})

0    Chris
1     Mary
2     John
Name: first_name, dtype: object

In [95]:
df_people

  first_name last_name     emails
0      Corey   Schafer   cs@gmail
1       Jane       Doe  jad@gmail
2       John     Smith  jod@gmail

In [97]:
#Replace
df_people['first_name']=df_people['first_name'].replace({'Corey':'Chris','Jane':'Mary'})

df_people

  first_name last_name     emails
0      Chris   Schafer   cs@gmail
1       Mary       Doe  jad@gmail
2       John     Smith  jod@gmail

In [98]:
df_public.rename(columns={'ConvertedComp':'SalaryUSD'}, inplace=True)

In [102]:
df_public[['SalaryUSD','Hobbyist']]

            SalaryUSD Hobbyist
Respondent
1                 NaN      Yes
2                 NaN       No
3              8820.0      Yes
4             61000.0       No
5                 NaN      Yes
...               ...      ...
88377             NaN      Yes
88601             NaN       No
88802             NaN       No
88816             NaN       No
88863             NaN      Yes

[88883 rows x 2 columns]

In [104]:
df_public['Hobbyist']=df_public['Hobbyist'].map({"Yes":True,"No":False})

In [105]:
df_public[['SalaryUSD','Hobbyist']]

            SalaryUSD  Hobbyist
Respondent
1                 NaN      True
2                 NaN     False
3              8820.0      True
4             61000.0     False
5                 NaN      True
...               ...       ...
88377             NaN      True
88601             NaN     False
88802             NaN     False
88816             NaN     False
88863             NaN      True

[88883 rows x 2 columns]