In [1]:
import pandas as pd

dfp=pd.read_csv('C:\\Users\\admin\\Desktop\\Data Science\\Data for ananlysis\\2019 developer survey Stackoverflow\\survey_results_public.csv'\
                     ,index_col='Respondent')

dfs=pd.read_csv('C:\\Users\\admin\\Desktop\\Data Science\\Data for ananlysis\\2019 developer survey Stackoverflow\\survey_results_schema.csv'\
                     ,index_col='Column')

dictionary={
    "first":["Corey","Jane","John"],
    "last":["Schafer","Doe","Doe"],
    "email":["sflajf@gmail","adjhdj@yahoo","adsfasfd@facebook"]
}

dfd=pd.DataFrame(dictionary)

# 10. Various types of files: excel,xlsx,json,etc

In [3]:
filt=(dfp['Country']=='India')
india_df=dfp.loc[filt]

In [ ]:
#csv
india_df.to_csv('C:\\Users\\admin\\Desktop\\Data Science\\Data for ananlysis\\2019 developer survey Stackoverflow\\modifiedIndia.csv')

In [4]:
#tsv
india_df.to_csv('C:\\Users\\admin\\Desktop\\Data Science\\Data for ananlysis\\2019 developer survey Stackoverflow\\modifiedIndia.tsv',sep='\t')

In [5]:
!pip install xlwt 
!pip install openpyxl 
!pip install xlrd

Requirement already satisfied: xlwt in c:\users\admin\anaconda3\lib\site-packages (1.3.0)
Requirement already satisfied: openpyxl in c:\users\admin\anaconda3\lib\site-packages (3.0.7)
Requirement already satisfied: et-xmlfile in c:\users\admin\anaconda3\lib\site-packages (from openpyxl) (1.0.1)
Requirement already satisfied: xlrd in c:\users\admin\anaconda3\lib\site-packages (2.0.1)

In [7]:
india_df.to_excel('C:\\Users\\admin\\Desktop\\Data Science\\Data for ananlysis\\2019 developer survey Stackoverflow\\modifiedIndia.xlsx')

In [8]:
test=pd.read_excel('C:\\Users\\admin\\Desktop\\Data Science\\Data for ananlysis\\2019 developer survey Stackoverflow\\modifiedIndia.xlsx',index_col='Respondent')
test.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,...,Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Difficult
15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
50,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Received on-the-job training in software devel...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,23.0,Man,No,NaN,South Asian,No,Too long,Easy
65,I am a developer by profession,Yes,Never,NaN,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",NaN,...,A lot more welcome now than last year,NaN,21.0,Man,No,NaN,NaN,Yes,Appropriate in length,Neither easy nor difficult

In [9]:
india_df.to_json('C:\\Users\\admin\\Desktop\\Data Science\\Data for ananlysis\\2019 developer survey Stackoverflow\\modifiedIndia.json')
#by default its dictionarylike

In [10]:
india_df.to_json('C:\\Users\\admin\\Desktop\\Data Science\\Data for ananlysis\\2019 developer survey Stackoverflow\\modifiedIndia.json',orient='records',lines=True)
#this json is list like

In [12]:
test=pd.read_json('C:\\Users\\admin\\Desktop\\Data Science\\Data for ananlysis\\2019 developer survey Stackoverflow\\modifiedIndia.json',orient='records',lines=True)
test.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,None,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,None,None,Appropriate in length,Neither easy nor difficult
1,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",None,None,...,Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,None,None,None,None,Yes,Too long,Difficult
2,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",None,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,None,None,Yes,Too long,Neither easy nor difficult
3,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Received on-the-job training in software devel...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,23.0,Man,No,None,South Asian,No,Too long,Easy
4,I am a developer by profession,Yes,Never,None,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",None,...,A lot more welcome now than last year,None,21.0,Man,No,None,None,Yes,Appropriate in length,Neither easy nor difficult

In [13]:
!pip install SQLAlchemy

Requirement already satisfied: SQLAlchemy in c:\users\admin\anaconda3\lib\site-packages (1.4.7)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\admin\anaconda3\lib\site-packages (from SQLAlchemy) (1.0.0)

In [14]:
!pip install psychopg2-binary

ERROR: Could not find a version that satisfies the requirement psychopg2-binary
ERROR: No matching distribution found for psychopg2-binary

# 9. Date Objects in DataFrame